language: go
services:
  - docker
  
go: 
 - 1.9
 - tip

script:
 - docker run -d -p 27017:27017 mongo
 - echo 'mode: atomic' > coverage.txt && go list ./... | xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp
 - go test -bench=.
 - go test -bench=./stores/in-memory
 - go test -bench=./stores/mongo

after_success:
  - bash <(curl -s https://codecov.io/bash)

  