language: go
services:
  - docker

before_install:
  - pip install awscli

go: 
 - 1.9
 - tip

# Note that the use of coverpkg here will cause some 'no packages being tested depend'
# warnings. But its easier to live with that than massively blow-out the package testing
# complexity.
script:
 - docker run -d -p 8000:8000 dwmkerr/dynamodb -sharedDb
 - docker run -d -p 27017:27017 mongo --master
 - docker run -d -p 2181:2181 -p 9092:9092 --env _KAFKA_advertised_host_name=127.0.0.1 --env _KAFKA_advertised_port=9092 flozano/kafka
 - aws dynamodb create-table --table-name test-store --attribute-definitions AttributeName=key,AttributeType=S AttributeName=sequence,AttributeType=N --key-schema AttributeName=key,KeyType=HASH AttributeName=sequence,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=100,WriteCapacityUnits=100 --endpoint-url http://localhost:8000
 - aws dynamodb create-table --table-name test-snap --attribute-definitions AttributeName=key,AttributeType=S --key-schema AttributeName=key,KeyType=HASH --provisioned-throughput ReadCapacityUnits=100,WriteCapacityUnits=100 --endpoint-url http://localhost:8000
 - "echo 'mode: atomic' > coverage.txt"
 - go list ./... | grep -v examples | xargs -n1 -I{} sh -c 'go test  -v -covermode=atomic -coverpkg ./... -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' 
 - rm coverage.tmp
 - go test -v -bench=.
 - go test -v -bench=./stores/in-memory
 - go test -v -bench=./stores/mongo

after_success:
  - bash <(curl -s https://codecov.io/bash)

  